// Mocks generated by Mockito 5.4.6 from annotations
// in homeworks/test/database/credentials_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:dart_untis_mobile/dart_untis_mobile.dart' as _i6;
import 'package:homeworks/database/models/credentials.dart' as _i5;
import 'package:homeworks/database/models/factory.dart' as _i11;
import 'package:homeworks/database/models/homework.dart' as _i3;
import 'package:homeworks/database/models/subject.dart' as _i4;
import 'package:homeworks/database/user.dart' as _i10;
import 'package:homeworks/utilities/cryptography.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomework_1 extends _i1.SmartFake implements _i3.Homework {
  _FakeHomework_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubject_2 extends _i1.SmartFake implements _i4.Subject {
  _FakeSubject_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUntisCredentials_3 extends _i1.SmartFake
    implements _i5.UntisCredentials {
  _FakeUntisCredentials_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUntisSession_4 extends _i1.SmartFake implements _i6.UntisSession {
  _FakeUntisSession_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CredentialCryptography].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialCryptography extends _i1.Mock
    implements _i7.CredentialCryptography {
  @override
  _i8.Future<String> databaseEncryption(
    String? userPassword,
    String? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #databaseEncryption,
          [
            userPassword,
            data,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #databaseEncryption,
            [
              userPassword,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #databaseEncryption,
            [
              userPassword,
              data,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> databaseDecryption(
    String? userPassword,
    String? encrypted,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #databaseDecryption,
          [
            userPassword,
            encrypted,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #databaseDecryption,
            [
              userPassword,
              encrypted,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #databaseDecryption,
            [
              userPassword,
              encrypted,
            ],
          ),
        )),
      ) as _i8.Future<String>);
}

/// A class which mocks [FirestoreUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreUser extends _i1.Mock implements _i10.FirestoreUser {
  @override
  _i2.DocumentReference<Map<String, dynamic>> get userDocument =>
      (super.noSuchMethod(
        Invocation.getter(#userDocument),
        returnValue: _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#userDocument),
        ),
        returnValueForMissingStub:
            _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#userDocument),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i8.Future<void> ensureDocumentExists() => (super.noSuchMethod(
        Invocation.method(
          #ensureDocumentExists,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [ItemFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemFactory extends _i1.Mock implements _i11.ItemFactory {
  @override
  _i3.Homework homeworkFromDocument(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #homeworkFromDocument,
          [data],
        ),
        returnValue: _FakeHomework_1(
          this,
          Invocation.method(
            #homeworkFromDocument,
            [data],
          ),
        ),
        returnValueForMissingStub: _FakeHomework_1(
          this,
          Invocation.method(
            #homeworkFromDocument,
            [data],
          ),
        ),
      ) as _i3.Homework);

  @override
  _i4.Subject subjectFromDocument(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #subjectFromDocument,
          [data],
        ),
        returnValue: _FakeSubject_2(
          this,
          Invocation.method(
            #subjectFromDocument,
            [data],
          ),
        ),
        returnValueForMissingStub: _FakeSubject_2(
          this,
          Invocation.method(
            #subjectFromDocument,
            [data],
          ),
        ),
      ) as _i4.Subject);

  @override
  _i5.UntisCredentials untisCredentialsFromJSON(String? jsonString) =>
      (super.noSuchMethod(
        Invocation.method(
          #untisCredentialsFromJSON,
          [jsonString],
        ),
        returnValue: _FakeUntisCredentials_3(
          this,
          Invocation.method(
            #untisCredentialsFromJSON,
            [jsonString],
          ),
        ),
        returnValueForMissingStub: _FakeUntisCredentials_3(
          this,
          Invocation.method(
            #untisCredentialsFromJSON,
            [jsonString],
          ),
        ),
      ) as _i5.UntisCredentials);

  @override
  _i8.Future<_i6.UntisSession> createUntisSession(
          _i5.UntisCredentials? creds) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUntisSession,
          [creds],
        ),
        returnValue: _i8.Future<_i6.UntisSession>.value(_FakeUntisSession_4(
          this,
          Invocation.method(
            #createUntisSession,
            [creds],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.UntisSession>.value(_FakeUntisSession_4(
          this,
          Invocation.method(
            #createUntisSession,
            [creds],
          ),
        )),
      ) as _i8.Future<_i6.UntisSession>);
}

/// A class which mocks [UntisCredentials].
///
/// See the documentation for Mockito's code generation for more information.
class MockUntisCredentials extends _i1.Mock implements _i5.UntisCredentials {
  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  String get school => (super.noSuchMethod(
        Invocation.getter(#school),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#school),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#school),
        ),
      ) as String);

  @override
  String get password => (super.noSuchMethod(
        Invocation.getter(#password),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#password),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#password),
        ),
      ) as String);

  @override
  String get server => (super.noSuchMethod(
        Invocation.getter(#server),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#server),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#server),
        ),
      ) as String);

  @override
  String toJsonString() => (super.noSuchMethod(
        Invocation.method(
          #toJsonString,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #toJsonString,
            [],
          ),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #toJsonString,
            [],
          ),
        ),
      ) as String);

  @override
  _i8.Future<String> calculateHash() => (super.noSuchMethod(
        Invocation.method(
          #calculateHash,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #calculateHash,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #calculateHash,
            [],
          ),
        )),
      ) as _i8.Future<String>);
}
