// Mocks generated by Mockito 5.4.6 from annotations
// in homeworks/test/database/homeworks_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:dart_untis_mobile/dart_untis_mobile.dart' as _i6;
import 'package:homeworks/database/models/credentials.dart' as _i5;
import 'package:homeworks/database/models/factory.dart' as _i10;
import 'package:homeworks/database/models/homework.dart' as _i3;
import 'package:homeworks/database/models/subject.dart' as _i4;
import 'package:homeworks/database/user.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomework_2 extends _i1.SmartFake implements _i3.Homework {
  _FakeHomework_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubject_3 extends _i1.SmartFake implements _i4.Subject {
  _FakeSubject_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUntisCredentials_4 extends _i1.SmartFake
    implements _i5.UntisCredentials {
  _FakeUntisCredentials_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUntisSession_5 extends _i1.SmartFake implements _i6.UntisSession {
  _FakeUntisSession_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreUser extends _i1.Mock implements _i7.FirestoreUser {
  @override
  _i2.DocumentReference<Map<String, dynamic>> get userDocument =>
      (super.noSuchMethod(
        Invocation.getter(#userDocument),
        returnValue: _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#userDocument),
        ),
        returnValueForMissingStub:
            _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#userDocument),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i8.Future<void> ensureDocumentExists() => (super.noSuchMethod(
        Invocation.method(
          #ensureDocumentExists,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [Homework].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomework extends _i1.Mock implements _i3.Homework {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get subjectDocId => (super.noSuchMethod(
        Invocation.getter(#subjectDocId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#subjectDocId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#subjectDocId),
        ),
      ) as String);

  @override
  bool get toNextLesson => (super.noSuchMethod(
        Invocation.getter(#toNextLesson),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isExam => (super.noSuchMethod(
        Invocation.getter(#isExam),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get fromUntis => (super.noSuchMethod(
        Invocation.getter(#fromUntis),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  DateTime get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#createdAt),
        ),
        returnValueForMissingStub: _FakeDateTime_1(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as DateTime);

  @override
  bool get isCompleted => (super.noSuchMethod(
        Invocation.getter(#isCompleted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get documentId => (super.noSuchMethod(
        Invocation.getter(#documentId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#documentId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#documentId),
        ),
      ) as String);

  @override
  bool get isUrgent => (super.noSuchMethod(
        Invocation.getter(#isUrgent),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isCompleted(bool? _isCompleted) => super.noSuchMethod(
        Invocation.setter(
          #isCompleted,
          _isCompleted,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dueDate(DateTime? _dueDate) => super.noSuchMethod(
        Invocation.setter(
          #dueDate,
          _dueDate,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toDocument() => (super.noSuchMethod(
        Invocation.method(
          #toDocument,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [ItemFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemFactory extends _i1.Mock implements _i10.ItemFactory {
  @override
  _i3.Homework homeworkFromDocument(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #homeworkFromDocument,
          [data],
        ),
        returnValue: _FakeHomework_2(
          this,
          Invocation.method(
            #homeworkFromDocument,
            [data],
          ),
        ),
        returnValueForMissingStub: _FakeHomework_2(
          this,
          Invocation.method(
            #homeworkFromDocument,
            [data],
          ),
        ),
      ) as _i3.Homework);

  @override
  _i4.Subject subjectFromDocument(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #subjectFromDocument,
          [data],
        ),
        returnValue: _FakeSubject_3(
          this,
          Invocation.method(
            #subjectFromDocument,
            [data],
          ),
        ),
        returnValueForMissingStub: _FakeSubject_3(
          this,
          Invocation.method(
            #subjectFromDocument,
            [data],
          ),
        ),
      ) as _i4.Subject);

  @override
  _i5.UntisCredentials untisCredentialsFromJSON(String? jsonString) =>
      (super.noSuchMethod(
        Invocation.method(
          #untisCredentialsFromJSON,
          [jsonString],
        ),
        returnValue: _FakeUntisCredentials_4(
          this,
          Invocation.method(
            #untisCredentialsFromJSON,
            [jsonString],
          ),
        ),
        returnValueForMissingStub: _FakeUntisCredentials_4(
          this,
          Invocation.method(
            #untisCredentialsFromJSON,
            [jsonString],
          ),
        ),
      ) as _i5.UntisCredentials);

  @override
  _i8.Future<_i6.UntisSession> createUntisSession(
          _i5.UntisCredentials? creds) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUntisSession,
          [creds],
        ),
        returnValue: _i8.Future<_i6.UntisSession>.value(_FakeUntisSession_5(
          this,
          Invocation.method(
            #createUntisSession,
            [creds],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.UntisSession>.value(_FakeUntisSession_5(
          this,
          Invocation.method(
            #createUntisSession,
            [creds],
          ),
        )),
      ) as _i8.Future<_i6.UntisSession>);
}
