// Mocks generated by Mockito 5.4.6 from annotations
// in homeworks/test/database/subjects_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:dart_untis_mobile/dart_untis_mobile.dart' as _i6;
import 'package:homeworks/database/models/credentials.dart' as _i5;
import 'package:homeworks/database/models/factory.dart' as _i10;
import 'package:homeworks/database/models/homework.dart' as _i3;
import 'package:homeworks/database/models/subject.dart' as _i4;
import 'package:homeworks/database/user.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomework_1 extends _i1.SmartFake implements _i3.Homework {
  _FakeHomework_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubject_2 extends _i1.SmartFake implements _i4.Subject {
  _FakeSubject_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUntisCredentials_3 extends _i1.SmartFake
    implements _i5.UntisCredentials {
  _FakeUntisCredentials_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUntisSession_4 extends _i1.SmartFake implements _i6.UntisSession {
  _FakeUntisSession_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_5 extends _i1.SmartFake implements _i7.Color {
  _FakeColor_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreUser extends _i1.Mock implements _i8.FirestoreUser {
  @override
  _i2.DocumentReference<Map<String, dynamic>> get userDocument =>
      (super.noSuchMethod(
        Invocation.getter(#userDocument),
        returnValue: _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#userDocument),
        ),
        returnValueForMissingStub:
            _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#userDocument),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i9.Future<void> ensureDocumentExists() => (super.noSuchMethod(
        Invocation.method(
          #ensureDocumentExists,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [ItemFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemFactory extends _i1.Mock implements _i10.ItemFactory {
  @override
  _i3.Homework homeworkFromDocument(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #homeworkFromDocument,
          [data],
        ),
        returnValue: _FakeHomework_1(
          this,
          Invocation.method(
            #homeworkFromDocument,
            [data],
          ),
        ),
        returnValueForMissingStub: _FakeHomework_1(
          this,
          Invocation.method(
            #homeworkFromDocument,
            [data],
          ),
        ),
      ) as _i3.Homework);

  @override
  _i4.Subject subjectFromDocument(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #subjectFromDocument,
          [data],
        ),
        returnValue: _FakeSubject_2(
          this,
          Invocation.method(
            #subjectFromDocument,
            [data],
          ),
        ),
        returnValueForMissingStub: _FakeSubject_2(
          this,
          Invocation.method(
            #subjectFromDocument,
            [data],
          ),
        ),
      ) as _i4.Subject);

  @override
  _i5.UntisCredentials untisCredentialsFromJSON(String? jsonString) =>
      (super.noSuchMethod(
        Invocation.method(
          #untisCredentialsFromJSON,
          [jsonString],
        ),
        returnValue: _FakeUntisCredentials_3(
          this,
          Invocation.method(
            #untisCredentialsFromJSON,
            [jsonString],
          ),
        ),
        returnValueForMissingStub: _FakeUntisCredentials_3(
          this,
          Invocation.method(
            #untisCredentialsFromJSON,
            [jsonString],
          ),
        ),
      ) as _i5.UntisCredentials);

  @override
  _i9.Future<_i6.UntisSession> createUntisSession(
          _i5.UntisCredentials? creds) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUntisSession,
          [creds],
        ),
        returnValue: _i9.Future<_i6.UntisSession>.value(_FakeUntisSession_4(
          this,
          Invocation.method(
            #createUntisSession,
            [creds],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.UntisSession>.value(_FakeUntisSession_4(
          this,
          Invocation.method(
            #createUntisSession,
            [creds],
          ),
        )),
      ) as _i9.Future<_i6.UntisSession>);
}

/// A class which mocks [Subject].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubject extends _i1.Mock implements _i4.Subject {
  @override
  _i7.Color get backColor => (super.noSuchMethod(
        Invocation.getter(#backColor),
        returnValue: _FakeColor_5(
          this,
          Invocation.getter(#backColor),
        ),
        returnValueForMissingStub: _FakeColor_5(
          this,
          Invocation.getter(#backColor),
        ),
      ) as _i7.Color);

  @override
  _i7.Color get foreColor => (super.noSuchMethod(
        Invocation.getter(#foreColor),
        returnValue: _FakeColor_5(
          this,
          Invocation.getter(#foreColor),
        ),
        returnValueForMissingStub: _FakeColor_5(
          this,
          Invocation.getter(#foreColor),
        ),
      ) as _i7.Color);

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get fromUntis => (super.noSuchMethod(
        Invocation.getter(#fromUntis),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get shortName => (super.noSuchMethod(
        Invocation.getter(#shortName),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#shortName),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#shortName),
        ),
      ) as String);

  @override
  String get documentId => (super.noSuchMethod(
        Invocation.getter(#documentId),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#documentId),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#documentId),
        ),
      ) as String);

  @override
  set nextLesson(DateTime? _nextLesson) => super.noSuchMethod(
        Invocation.setter(
          #nextLesson,
          _nextLesson,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toDocument() => (super.noSuchMethod(
        Invocation.method(
          #toDocument,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
