// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-XT92AKMSSoAqlEhGET8tVLKWdPyRqoI',
    appId: '1:626284965826:web:ed0ab9c6a5c2ee9ed1f05b',
    messagingSenderId: '626284965826',
    projectId: 'homework-manager-untis',
    authDomain: 'homework-manager-untis.firebaseapp.com',
    databaseURL:
        'https://homework-manager-untis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homework-manager-untis.firebasestorage.app',
    measurementId: 'G-0VCS9KKWM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW6UTg1EzKPFLB6mkn5EvsZ9HH0Ez3m5E',
    appId: '1:626284965826:android:fb5237955242d6f1d1f05b',
    messagingSenderId: '626284965826',
    projectId: 'homework-manager-untis',
    databaseURL:
        'https://homework-manager-untis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homework-manager-untis.firebasestorage.app',
  );
}
