# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy IOS build"
  lane :build_adhoc do
    create_keychain(
      name: "ci-signing",
      password: ENV["IOS_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
      certificate_path: ENV["IOS_P12_PATH"],
      certificate_password: ENV["IOS_P12_PASSWORD"],
      keychain_name: "ci-signing",
      keychain_password: ENV["IOS_KEYCHAIN_PASSWORD"]
    )

    install_provisioning_profile(
      path: ENV["IOS_PROFILE_PATH"]
    )

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "ad-hoc",
      output_directory: "build/ios/ipa",
      output_name: "app.ipa"
    )
  end
end
