# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build IOS App"
  lane :build do
    create_keychain(
      name: "ci-signing",
      password: ENV["IOS_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
      certificate_path: ENV["IOS_P12_PATH"],
      certificate_password: ENV["IOS_P12_PASSWORD"],
      keychain_name: "ci-signing",
      keychain_password: ENV["IOS_KEYCHAIN_PASSWORD"]
    )

    sh("security default-keychain")
    sh("security list-keychains")
    sh("security find-identity -v -p codesigning")

    install_provisioning_profile(
      path: ENV["IOS_PROFILE_PATH"]
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "../ios/Runner.xcodeproj",

      team_id: ENV["APPLE_TEAM_ID"],
      bundle_identifier: ENV["IOS_BUNDLE_ID"],
      profile_name: ENV["IOS_PROFILE_NAME"],

      code_sign_identity: "Apple Distribution"
    )

    build_app(
      workspace: "../ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "ad-hoc",
      export_team_id: ENV["APPLE_TEAM_ID"],
      export_options: {
      provisioningProfiles: {
          ENV["IOS_BUNDLE_ID"] => ENV["IOS_PROFILE_NAME"]
        }
      },
      output_directory: "../build/ios/ipa",
      output_name: "app.ipa",
      
      buildlog_path: "../buildlogs",
      result_bundle: true,
      result_bundle_path: "../build/ios/Runner.xcresult"
    )

    upload_symbols_to_crashlytics(
      dsym_path: lane_context[SharedValues::DSYM_OUTPUT_PATH],
      app_id: "1:626284965826:ios:a0380d8279a58f25d1f05b"
    )
  end

  desc "Deploy IOS App zu Testflight"
  lane :deploy_testflight do
    build    

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true
    )


    upload_to_testflight(
      ipa: "../build/ios/ipa/app.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
