name: IOS Build

on: push # To test this workflow, run on every push.defaults:
# CHANGE THIS BEFORE MERGING TO MAIN BRANCH

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: false # To test this workflow, do not run tests. REMOVE THIS LINE BEFORE MERGING TO MAIN BRANCH
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
          key: ${{ runner.os }}-flutter-dependencies-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-dependencies
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Run build runner
        run: dart run build_runner build

      - name: Run tests
        run: flutter test
    
  build:
    name: Build iOS App
    # needs: test # do not wait for test when testing this workflow
    # CHANGE THIS LINE BEFORE MERGING TO MAIN BRANCH 
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          cache: true     
          
      - name: Restore Dependencies Cache
        uses: actions/cache/restore@v4
        id: flutter-deps-cache
        with:
          path: |
            ~/.pub-cache
            ~/Library/Developer/Xcode/DerivedData/*/SourcePackages
            ~/Library/Caches/org.swift.swiftpm
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
          key: ${{ runner.os }}-flutter-dependencies-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-dependencies
      
      - name: Install dependencies
        run: |
          flutter pub get
          flutter build ios --config-only --no-codesign

      - name: Save Cache Dependencies
        uses: actions/cache/save@v4
        if: steps.flutter-deps-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.pub-cache
            ~/Library/Developer/Xcode/DerivedData/*/SourcePackages
            ~/Library/Caches/org.swift.swiftpm
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
          key:  ${{ steps.flutter-deps-cache.outputs.cache-primary-key }}
      
      - name: Flutter Setup
        if: false # To test this workflow, do not run long setup commands. REMOVE THIS LINE BEFORE MERGING TO MAIN BRANCH
        run: |
            dart run build_runner build
            dart run flutter_launcher_icons
            dart run flutter_native_splash:create

      - name: Setup signing file env
        run: |          
          echo "IOS_P12_PASSWORD=$(openssl rand -hex 32)" >> "$GITHUB_ENV"
          echo "IOS_KEYCHAIN_PASSWORD=$(openssl rand -hex 32)" >> "$GITHUB_ENV"
          echo "IOS_P12_PATH=$RUNNER_TEMP/distribution.p12" >> "$GITHUB_ENV"
          echo "IOS_PROFILE_PATH=$RUNNER_TEMP/profile.mobileprovision" >> "$GITHUB_ENV"

      - name: Restore iOS signing files
        env:
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          IOS_PRIVATE_KEY_BASE64: ${{ secrets.IOS_PRIVATE_KEY_BASE64 }}
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          # IOS_P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
        run: |
          echo "Decoding iOS signing files ..."
          echo -n "$IOS_CERTIFICATE_BASE64" \
            | base64 --decode > "$RUNNER_TEMP/distribution.cer"

          echo -n "$IOS_PRIVATE_KEY_BASE64" \
            | base64 --decode > "$RUNNER_TEMP/distribution.key"

          echo -n "$IOS_PROVISIONING_PROFILE_BASE64" \
            | base64 --decode > "$IOS_PROFILE_PATH"
          
          echo "Creating P12 file from certificate and private key ..."
          openssl x509 \
            -inform DER \
            -in "$RUNNER_TEMP/distribution.cer" \
            -out "$RUNNER_TEMP/distribution.pem"

          openssl pkcs12 -export \
            -legacy \
            -inkey "$RUNNER_TEMP/distribution.key" \
            -in "$RUNNER_TEMP/distribution.pem" \
            -out "$IOS_P12_PATH" \
            -passout env:IOS_P12_PASSWORD


      - name: Verify iOS signing files
        run: |
          echo "Opening the P12 file ..."
          openssl pkcs12 \
            -legacy \
            -in "$IOS_P12_PATH" \
            -passin env:IOS_P12_PASSWORD \
            -noout
          
          echo "Checking hash of the certificate and private key ..."
          openssl x509 \
            -in "$RUNNER_TEMP/distribution.pem" \
              -pubkey -noout \
              | openssl sha256

          openssl pkey \
            -in "$RUNNER_TEMP/distribution.key" \
            -pubout \
            | openssl sha256

      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.12
          bundler-cache: true

      - name: Install Fastlane
        run: |
          cd ios
          gem install fastlane
        

      - name: Build signed iOS IPA
        env:
          # IOS_KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
          APPLE_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          IOS_BUNDLE_ID: ${{ vars.IOS_BUNDLE_ID }}
          IOS_PROFILE_NAME: ${{ vars.IOS_PROFILE_NAME }}
        run: |
          cd ios
          bundle exec fastlane ios build_adhoc

      - name: Upload IPA as GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-adhoc
          path: build/ios/ipa/app.ipa

  cache-flutter:
    if: false
    name: Install Flutter for caching
    runs-on: macos-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          cache: true     